version: '3.1'

services:
  nuxt:
    build: .
    restart: always
    volumes:
      - .:/data/docker/frontend
    working_dir: /data/docker/frontend
    command: "pm2-runtime start ecosystem.config.cjs"
    ports:
      - "3000:3000"
